---
# Global variables for all hosts
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_python_interpreter: /usr/bin/python3

# WanderList Application Settings
wanderlist:
  app_name: wanderlist
  version: latest
  port: 3000
  replicas: 3
  
# Database Configuration
database:
  host: postgres-service
  port: 5432
  name: wanderlistdb
  user: wanderlist_user
  # Note: Password should be in vault or secrets
  
# Monitoring Configuration
monitoring:
  prometheus_port: 9090
  grafana_port: 3000
  grafana_admin_password: admin123
  scrape_interval: 15s
  
# Kubernetes Configuration
kubernetes:
  namespace: default
  monitoring_namespace: monitoring
  
# Docker Configuration
docker:
  registry: docker.io
  image_pull_policy: Always